# Generated by Django 3.2.25 on 2025-09-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(db_index=True, max_length=100, verbose_name='Номенклатура')),
                ('document_number', models.CharField(db_index=True, max_length=50, verbose_name='Номер документа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('old_order', models.CharField(max_length=50, verbose_name='Старый заказ')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('resource', models.CharField(max_length=50, verbose_name='Ресурс')),
                ('new_order', models.CharField(max_length=50, verbose_name='Новый заказ')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-date', 'document_number'],
            },
        ),
    ]
